# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62e3e4245426cacd0b211dee596b722affcf39b228d31f17f2f141b614b0a0eb19eeebe5d20db244babb35f2c560f863f2348e419cdb5bb77ae249adb65d6bb9

test:
  secret_key_base: 1262eb40e42c1b1551accc0a9f4232cb36dc5e19009fc9db5a9befee0c6a8d8852969249c86791875f393c61509d4212a24bc3076334b51028fc7fd944848e88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
